\TEMPLATE_START//********************************************
//                                         
//  EASEA.cpp
//                                         
//  C++ file generated by AESAE-EO Millennium Edition (v0.6)
//                                         
//********************************************

\ANALYSE_PARAMETERS
\INSERT_USER_DECLARATIONS
\INSERT_INITIALISATION_FUNCTION \ANALYSE_USER_CLASSES
\INSERT_USER_CLASSES

\GENOME_CTOR 

\GENOME_CTOR

\GENOME_DTOR  
\INSERT_GENOME

\GENOME_DTOR
\COPY_CTOR  
\READ
\WRITE
\INSERT_USER_FUNCTIONS
\INSERT_INITIALISER

\INSERT_CROSSOVER

\INSERT_MUTATOR

\INSERT_EVALUATOR
\INSERT_INIT_FCT_CALL

\SELECTORS
\REPL_PERC

  \REPLACEMENT
  \ELITIST_REPLACE_NAME
  \DISCARD_PRM
\ELITISM
\TEMPLATE_END

