# action originating from CMake action
name: Faster-CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  pre-ci:
    name: Configure workflow
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.extract_branch.outputs.branch }}

    steps:
      - uses: actions/checkout@v3
      - name: Extract branch name
        id: extract_branch
        shell: bash
        run: |
          TMP_PULL_HEAD_REF="${{ github.head_ref }}"
          TMP_GITHUB_REF="${GITHUB_REF#refs/heads/}"
          EXPORT_VALUE=""
          if [ "${TMP_PULL_HEAD_REF}" != "" ]
          then
              EXPORT_VALUE="${TMP_PULL_HEAD_REF}"
          else
              EXPORT_VALUE="${TMP_GITHUB_REF}"
          fi
          echo "::set-output name=branch::${EXPORT_VALUE}"

  Linux:
    name: Test application (Linux)
    runs-on: ubuntu-latest
    needs: [pre-ci]
    outputs:
      configure: ${{ steps.cmake-configure.outcome }}
      build: ${{ steps.cmake-build.outcome }}
      install: ${{ steps.cmake-install.outcome }}
      total: ${{ steps.status.outputs.total }}
      passed: ${{ steps.status.outputs.passed }}
      failed: ${{ steps.status.outputs.failed }}

    steps:
      - uses: actions/checkout@v3

      - name: Installing dependencies
        run: sudo apt install -y libboost-all-dev

      - name: Installing CUDA toolkit
        uses: Jimver/cuda-toolkit@v0.2.7
        with:
          cuda: '11.7.0'

      - name: CMake configure
        id: cmake-configure
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        shell: bash

      - name: CMake build
        id: cmake-build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
        shell: bash

      - name: CMake Install
        id: cmake-install
        run: sudo cmake --install ${{github.workspace}}/build
        shell: bash

      - name: Upload installation artifacts
        uses: actions/upload-artifact@v3
        with:
          name: installed-Linux
          path: /usr/local/easena

      - name: Build examples
        run: |
          EZ_PATH=/usr/local/easena/ bash ${{github.workspace}}/examples/build-all.sh "/usr/local/easena/bin/easena" | tee examples.output
          result_code=${PIPESTATUS[0]}
          exit $result_code
        shell: bash
      
      - name: Output examples status
        id: status
        if: ${{ always() }}
        run: |
          LINE=$(cat examples.output | sed -n 's/passed://p' | sed -n 's/\(.\[[[:digit:]]\+\)*\(;[[:digit:]]\+\)*\(m\)*//pg')
          NBE=$(echo ${LINE} | sed -n 's/\([[:digit:]]\+\)\/\([[:digit:]]\+\)/\2/p')
          PASSED=$(echo ${LINE} | sed -n 's/\([[:digit:]]\+\)\/\([[:digit:]]\+\)/\1/p')
          FAILED=$((NBE - PASSED))
          echo "::set-output name=total::${NBE}"
          echo "::set-output name=passed::${PASSED}"
          echo "::set-output name=failed::${FAILED}"
        shell: bash

  MacOS:
    name: Test application (MacOS)
    runs-on: macos-latest
    needs: [pre-ci]
    outputs:
      configure: ${{ steps.cmake-configure.outcome }}
      build: ${{ steps.cmake-build.outcome }}
      install: ${{ steps.cmake-install.outcome }}
      total: ${{ steps.status.outputs.total }}
      passed: ${{ steps.status.outputs.passed }}
      failed: ${{ steps.status.outputs.failed }}

    steps:
      - uses: actions/checkout@v3

      - name: Installing dependencies
        shell: bash
        run: |
          brew install bison libomp coreutils boost gnu-sed
          export PATH="$(brew --prefix bison)/bin:$PATH"
          export PATH="$(brew --prefix)/opt/gnu-sed/libexec/gnubin:$PATH"

      - name: CMake configure
        id: cmake-configure
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        shell: bash

      - name: CMake build
        id: cmake-build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
        shell: bash

      - name: CMake Install
        id: cmake-install
        run: sudo cmake --install ${{github.workspace}}/build
        shell: bash

      - name: Upload installation artifacts
        uses: actions/upload-artifact@v3
        with:
          name: installed-MacOS
          path: /usr/local/easena

      - name: Build examples
        run: |
          EZ_PATH=/usr/local/easena/ bash ${{github.workspace}}/examples/build-all.sh "/usr/local/easena/bin/easena" | tee examples.output
          result_code=${PIPESTATUS[0]}
          exit $result_code
        shell: bash
      
      - name: Output examples status
        id: status
        if: ${{ always() }}
        run: |
          LINE=$(cat examples.output | sed -n 's/passed://p' | sed -n 's/\(.\[[[:digit:]]\+\)*\(;[[:digit:]]\+\)*\(m\)*//pg')
          NBE=$(echo ${LINE} | sed -n 's/\([[:digit:]]\+\)\/\([[:digit:]]\+\)/\2/p')
          PASSED=$(echo ${LINE} | sed -n 's/\([[:digit:]]\+\)\/\([[:digit:]]\+\)/\1/p')
          FAILED=$((NBE - PASSED))
          echo "::set-output name=total::${NBE}"
          echo "::set-output name=passed::${PASSED}"
          echo "::set-output name=failed::${FAILED}"
        shell: bash

  Windows:
    name: Test application (Windows)
    runs-on: windows-latest
    needs: [pre-ci]
    outputs:
      configure: ${{ steps.cmake-configure.outcome }}
      build: ${{ steps.cmake-build.outcome }}
      install: ${{ steps.cmake-install.outcome }}
      total: ${{ steps.status.outputs.total }}
      passed: ${{ steps.status.outputs.passed }}
      failed: ${{ steps.status.outputs.failed }}

    steps:
      - uses: actions/checkout@v3

      - name: Installing dependencies
        run: choco install winflexbison3 boost-msvc-14.3 sed
        shell: bash

      - name: CMake configure
        id: cmake-configure
        run: cmake -B ./build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        shell: bash

      - name: CMake build
        id: cmake-build
        run: cmake --build ./build --config ${{env.BUILD_TYPE}}
        shell: bash

      - name: CMake Install
        id: cmake-install
        run: sudo cmake --install ./build
        shell: bash

      - name: Upload installation artifacts
        uses: actions/upload-artifact@v3
        with:
          name: installed-Windows
          path: C:/Program Files (x86)/EASENA/

      - name: Build examples
        run: |
          EZ_PATH="C:/Program Files (x86)/EASENA/" bash ${{github.workspace}}/examples/build-all.sh "C:/Program Files (x86)/EASENA/bin/easena.exe" --no-cuda | tee examples.output
          result_code=${PIPESTATUS[0]}
          exit $result_code
        shell: bash

      - name: Output examples status
        id: status
        if: ${{ always() }}
        run: |
          LINE=$(cat examples.output | sed -n 's/passed://p' | sed -n 's/\(.\[[[:digit:]]\+\)*\(;[[:digit:]]\+\)*\(m\)*//pg')
          NBE=$(echo ${LINE} | sed -n 's/\([[:digit:]]\+\)\/\([[:digit:]]\+\)/\2/p')
          PASSED=$(echo ${LINE} | sed -n 's/\([[:digit:]]\+\)\/\([[:digit:]]\+\)/\1/p')
          FAILED=$((NBE - PASSED))
          echo "::set-output name=total::${NBE}"
          echo "::set-output name=passed::${PASSED}"
          echo "::set-output name=failed::${FAILED}"
        shell: bash


          # badges:
          #   runs-on: ubuntu-latest
          #   name: Create badges
          #   needs: [pre-ci, configure, build, install, test]
          #   if: ${{ always() }}
          #
          #   steps:
          #     - uses: actions/checkout@v3
          #       with:
          #         ref: badges
          #
          #     - run: mkdir -p badges
          #     - run: echo ${{ needs.configure.outputs.status }}  ${{ needs.build.outputs.status }} ${{ needs.install.outputs.status }} ${{ needs.test.outputs.total }} ${{ needs.test.outputs.passed }} ${{ needs.test.outputs.failed }}
          #
          #     - name: Generate configure badge
          #       uses: emibcn/badge-action@v1
          #       with:
          #         label: 'configure'
          #         status: ${{ needs.configure.outputs.status == 'success' && 'passed' || 'failed' }}
          #         color: ${{ needs.configure.outputs.status == 'success' && 'green' || 'red' }}
          #         path: badges/configure.svg
          #
          #     - name: Generate build badge
          #       uses: emibcn/badge-action@v1
          #       with:
          #         label: 'build'
          #         status: ${{ needs.build.outputs.status == 'success' && 'passed' || 'failed' }}
          #         color: ${{ needs.build.outputs.status == 'success' && 'green' || 'red' }}
          #         path: badges/build.svg
          #
          #     - name: Generate install badge
          #       uses: emibcn/badge-action@v1
          #       with:
          #         label: 'install'
          #         status: ${{ needs.install.outputs.status == 'success' && 'passed' || 'failed' }}
          #         color: ${{ needs.install.outputs.status == 'success' && 'green' || 'red' }}
          #         path: badges/install.svg
          #
          #     - name: Generate test badge if all failed
          #       uses: emibcn/badge-action@v1
          #       if: ${{ needs.test.outputs.total == '' }}
          #       with:
          #         label: 'test'
          #         status: 'ERROR'
          #         color: 'red'
          #         path: badges/test.svg
          #
          #     - name: Generate test badge if run
          #       uses: emibcn/badge-action@v1
          #       if: ${{ needs.test.outputs.total != '' }}
          #       with:
          #         label: 'Working examples'
          #         status: ${{ needs.test.outputs.passed }}/${{ needs.test.outputs.total }}
          #         color: ${{ needs.test.outputs.failed == '0' && 'green' ||
          #                   needs.test.outputs.failed >= 1 && needs.test.outputs.failed <= 3 && 'yellow' ||
          #                   needs.test.outputs.failed >= 3 && needs.test.outputs.failed <= 6 && 'orange' ||
          #                   'red' }}
          #         path: badges/test.svg
          #
          #     - name: Commit badge
          #       env:
          #         BRANCH: ${{ needs.pre-ci.outputs.branch }}
          #       working-directory: ./badges
          #       run: |
          #         git config --local user.email "action@github.com"
          #         git config --local user.name "GitHub Action"
          #         mkdir -p "${BRANCH}"
          #         mv *.svg "${BRANCH}"
          #         git add "${BRANCH}/"
          #         # Will give error if badge did not changed
          #         git commit -m "Add/Update badge for branch: ${BRANCH}" || true
          #
          #     - name: Push badge commit
          #       uses: ad-m/github-push-action@master
          #       with:
          #         github_token: ${{ secrets.GITHUB_TOKEN }}
          #         branch: badges
          #         directory: badges
